# Generated by Django 5.0.3 on 2024-03-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='products',
            new_name='productsJson',
        ),
        migrations.AddField(
            model_name='transaction',
            name='produits',
            field=models.ManyToManyField(related_name='transactions', to='quickstart.produit'),
        ),
    ]
