# Generated by Django 5.0.3 on 2024-03-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_products_transaction_productsjson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='productsJson',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='produits',
        ),
        migrations.CreateModel(
            name='TransactionProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.FloatField()),
                ('prixSolde', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.produit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quickstart.transaction')),
            ],
        ),
    ]
