# Generated by Django 5.0.3 on 2024-03-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_remove_transaction_productsjson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionproduit',
            name='prixSolde',
            field=models.FloatField(null=True),
        ),
    ]
